<?php

namespace Database\Seeders;

use App\Models\Product;
use Illuminate\Database\Seeder;

class ProductSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $products = [
            [
                //'id' => 1,
                'name' => 'Mondo SkimCoat 20kg',
                'slug' => 'mondo-skimcoat-20kg',
                //'s_description' => 'Superior strength and durability.',
                'description' => 'Provides outstanding adhesion to water based paint system.',
                'selling_price' => '470.00',

                'quantity' => '50',
                'image' => 'images/products/' . 1 .'.jpg',
                'category_id' => '3',
                'brand_id' => '2',
            ],
            [
                //'id' => 2,
                'name' => 'Ultra Fino Skimcoat 20kg',
                'slug' => 'ultra-fino-skimcoat-20kg',
                //'s_description' => 'Concrete surface finisher.',
                'description' => 'UltraFino Skimcoat cement-based powder for thin plastering applications. When mixed with wate, the smooth creamy consistency makes it easy to correct surface imperfections prior to painting.',
                'selling_price' => '430.00',

                'quantity' => '38',
                'image' => 'images/products/' . 2 .'.jpg',
                'category_id' => '3',
                'brand_id' => '3',
            ],
            [
                //'id' => 3,
                'name' => 'Standard Brass Padlock 50mm',
                'slug' => 'standard-brass-padlock-50mm',
                //'s_description' => 'Is suited for indoor or outdoor use.',
                'description' => 'Constructed with brass pins, stainless steel springs and a double locking hardened steel shackle.',
                'selling_price' => '850.00',

                'quantity' => '38',
                'image' => 'images/products/' . 3 .'.jpg',
                'category_id' => '4',
                'brand_id' => '4',
            ],
            [
                //'id' => 4,
                'name' => 'Philips LED Light Bulb 10W',
                'slug' => 'philips-led-10w',
                //'s_description' => 'Philips interfaced option provide an optimal light and comfort.',
                'description' => 'Improve your home’s atmosphere with Philips high-performance and energy-saving light bulbs.',
                'selling_price' => '169.00',

                'quantity' => '10',
                'image' => 'images/products/' . 4 .'.jpg',
                'category_id' => '2',
                'brand_id' => '5',
            ],
            [
                //'id' => 5,
                'name' => 'Tokina Gas Regulator',
                'slug' => 'tokina-gas-regulator',
                //'s_description' => 'With adjustable pressure knob with gauge and anti explode.',
                'description' => 'With Anti Explode Safety Feature and Adjustable Flow Control Gasul Ball Type Fitting for a more secure and easier installation. Denmark Technology and Quality Guaranteed.',
                'selling_price' => '250.00',

                'quantity' => '5',
                'image' => 'images/products/' . 5 .'.jpg',
                'category_id' => '5',
                'brand_id' => '6',
            ],
            [
                //'id' => 6,
                'name' => 'Marine Plywood 1/4',
                'slug' => 'marine-plywood-1-4',
                //'s_description' => 'it is made of poplar wood which has medium low capacity, water resistant and ideal for boat making, home building and furniture making.',
                'description' => 'Manufactured from softwoods (such as Douglas fir, pine, and redwood), hardwoods (such as ash, maple, and mahogany), or a combination of both. The timber used to make plywood is prepared by steaming or dipping in hot water. It is then peeled into thin plies of between 1-4 mm by a lathe machine.',
                'selling_price' => '370.00',

                'quantity' => '92',
                'image' => 'images/products/' . 6 .'.jpg',
                'category_id' => '6',
                'brand_id' => '7',
            ],
            [
                //'id' => 7,
                'name' => 'Marine Plywood 3/4',
                'slug' => 'marine-plywood-3-4',
                //'s_description' => 'Waterproof marine grade plywood for building and construction.',
                'description' => 'Manufactured from softwoods (such as Douglas fir, pine, and redwood), hardwoods (such as ash, maple, and mahogany), or a combination of both. The timber used to make plywood is prepared by steaming or dipping in hot water. It is then peeled into thin plies of between 1-4 mm by a lathe machine.',
                'selling_price' => '999.00',

                'quantity' => '64',
                'image' => 'images/products/' . 7 .'.jpg',
                'category_id' => '6',
                'brand_id' => '7',
            ],
            [
                //'id' => 8,
                'name' => 'Marine Plywood Sanepa 9mm',
                'slug' => 'marine-plywood-sanepa-9mm',
                //'s_description' => 'Its quality is known to withstand any weather condition makes it the ideal plywood for boat-making, home building and furniture-making.',
                'description' => 'Santa Clara Marine Plywood is produced locally from two manufacturing plants in Davao and Agusan. Each sheet of Santa Clara Marine Plywood carries the distinct quality seal after passing SMWPI’s stringent quality assurances process. This ensures all products delivered to local and international clients have met quality and worksmanship standards.',
                'selling_price' => '1610.00',

                'quantity' => '105',
                'image' => 'images/products/' . 8 .'.jpg',
                'category_id' => '6',
                'brand_id' => '7',
            ],
            [
                //'id' => 9,
                'name' => 'Marine Plywood Hardflex 4x8 12mm',
                'slug' => 'marine-plywood-hardflex-4x8-12mm',
                //'s_description' => 'Full eucalytpus hardwood, best grade.',
                'description' => 'Marine hardflex Plywood carries the distinct quality seal after passing SMWPI’s stringent quality assurances process. This ensures all products delivered to local and international clients have met quality and worksmanship standards.',
                'selling_price' => '1590.00',

                'quantity' => '87',
                'image' => 'images/products/' . 9 .'.jpg',
                'category_id' => '6',
                'brand_id' => '7',
            ],
            [
                //'id' => 10,
                'name' => 'Marine Plywood Crocodile 1/2',
                'slug' => 'marine-plywood-crocodile-1-2',
                //'s_description' => 'Best phenolic board, film faced plywood 1/2 phenolic board crocodile phenolic.',
                'description' => 'Santa Clara Marine Plywood is produced locally from two manufacturing plants in Davao and Agusan. Each sheet of Santa Clara Marine Plywood carries the distinct quality seal after passing SMWPI’s stringent quality assurances process. This ensures all products delivered to local and international clients have met quality and worksmanship standards.',
                'selling_price' => '655.00',

                'quantity' => '70',
                'image' => 'images/products/' . 10 .'.jpg',
                'category_id' => '6',
                'brand_id' => '7',
            ],
            [
                //'id' => 11,
                'name' => 'PVC Pipe Black 82mm',
                'slug' => 'pvc-pipe-black-82mm',
                //'s_description' => 'PVC Pipe is used to create an access point for pipe cleaning and inspection in existing upvc soil pipe.',
                'description' => 'PVC Pipe is used for water supply and drainage, high quality. PVC pipe extrusion line with new technology, stable operation.',
                'selling_price' => '699.00',

                'quantity' => '25',
                'image' => 'images/products/' . 11 .'.jpg',
                'category_id' => '4',
                'brand_id' => '8',
            ],
            [
                //'id' => 12,
                'name' => 'PVC Orange Clamp 1/2',
                'slug' => 'pvc-orange-clamp-1-2',
                //'s_description' => 'This is used to secure 1/2" sized electrical pipes on concrete /wood surfaces.',
                'description' => 'A pipe clamp is a type of clamp often employed in woodworking, piping or cabinet shops. When referring to woodwork or cabinet shops, pipe clamps are usually composed of commercially manufactured clamp heads or "jaws" and a length of common threaded pipe. The capacity of the clamp is determined by the length of the pipe used. When referring to piping, pipe clamps are used to connect the pipe to the pipe hanger assembly.',
                'selling_price' => '20.00',

                'quantity' => '25',
                'image' => 'images/products/' . 12 .'.jpg',
                'category_id' => '4',
                'brand_id' => '9',
            ],
            [
                //'id' => 13,
                'name' => 'PVC Elbow 90',
                'slug' => 'pvc-elbow-90',
                //'s_description' => 'PVC elbow 90 degrees are the most common type ofelbowand used when space is available and flow is more critical.',
                'description' => 'PVC elbow 90 degrees is used to connect a piece of pipe with a threaded fitting to form an angle of 90 degrees. Also, it allows the user to connect two different size pipes at a 90-degree angle when one pipe has a smooth exterior and the other has a male pipe thread.',
                'selling_price' => '50.00',

                'quantity' => '139',
                'image' => 'images/products/' . 13 .'.jpg',
                'category_id' => '4',
                'brand_id' => '8',
            ],
            [
                //'id' => 14,
                'name' => 'Neltex Clean Out',
                'slug' => 'neltex-clean-out',
                //'s_description' => 'Extremely tough, suitable for long-term use.',
                'description' => 'With its ultra high resistance to impact damage and ultra strong tensile strength, it can withstand adverse condition. It exceeds the BPS standard by at least 7 times higher. Ideal for the more discerning users, the ULTIMA SUPRA SERIES provide ultra high impact strength.',
                'selling_price' => '560.00',

                'quantity' => '28',
                'image' => 'images/products/' . 14 .'.jpg',
                'category_id' => '4',
                'brand_id' => '8',
            ],
            [
                //'id' => 15,
                'name' => 'PVC Blue Coupling 1/2',
                'slug' => 'pvc-blue-coupling-1-2',
                //'s_description' => 'This is Commonly used in laying pipes for potable water supply.',
                'description' => 'Couplings are one of the most simple (and inexpensive) types of PVC fittings. They are a small part that connects or "couples" one part to another, usually permanently. They can connect pipe to pipe and pipe to fitting.',
                'selling_price' => '70.00',

                'quantity' => '30',
                'image' => 'images/products/' . 15 .'.jpg',
                'category_id' => '4',
                'brand_id' => '10',
            ],
            [
                //'id' => 16,
                'name' => 'Firefly Weatherproof Socket',
                'slug' => 'firefly-weatherproof-socket',
                //'s_description' => 'Firefly Rubber Weatherproof Socket Receptacle E27 for Indoor and Outdoor 4A 250V.',
                'description' => 'Firefly Weatherproof Socket is 4A 250V Weatherproof Socket used indoors or outdoors to create string of lights.',
                'selling_price' => '65.00',

                'quantity' => '40',
                'image' => 'images/products/' . 16 .'.jpg',
                'category_id' => '4',
                'brand_id' => '1',
            ],
            [
                //'id' => 17,
                'name' => 'Universal Socket Adaptor',
                'slug' => 'universal-socket-adaptor',
                //'s_description' => 'Universal World Wide Travel Charger Adapter Plug.',
                'description' => 'Universal Socket Adaptor can connect your electrical appliance everywhere around the world. The insides of Omni adapters are made of copper. Which make them durable and highly conductive.',
                'selling_price' => '75.00',

                'quantity' => '50',
                'image' => 'images/products/' . 17 .'.jpg',
                'category_id' => '4',
                'brand_id' => '11',
            ],
            [
                //'id' => 18,
                'name' => 'Swing Type Plug',
                'slug' => 'swing-type-plug',
                //'s_description' => 'Insides of Omni electrical plugs are made of copper.',
                'description' => 'Conforms to IEC Standards. With grounding terminal. Withstands over 5000 outlet operations, High impact and mechanical strength, cast aluminum enclosure.',
                'selling_price' => '87.00',

                'quantity' => '35',
                'image' => 'images/products/' . 18 .'.jpg',
                'category_id' => '4',
                'brand_id' => '11',
            ],
            [
               //'id' => 19,
                'name' => 'Royu 1 Gang Outlet',
                'slug' => 'royu-1-gang-outlet',
                //'s_description' => 'Power connection devices used in domestic and light commercial environments.',
                'description' => 'Royu Classic Series Plate 1 gang, blank and with cover.Weather-Proof Plate Cover Slim Type (RCP6)',
                'selling_price' => '125.00',

                'quantity' => '65',
                'image' => 'images/products/' . 19 .'.jpg',
                'category_id' => '4',
                'brand_id' => '12',
            ],
            [
                //'id' => 20,
                'name' => 'Royu 2 Gang Outlet Dark Gray',
                'slug' => 'royu-2-gang-outlet-dark-gray',
                //'s_description' => 'Power connection devices used in domestic and light commercial environments.',
                'description' => 'Royu Classic Series Plate 2 gang, blank and with cover.Weather-Proof Plate Cover Slim Type (RCP6)',
                'selling_price' => '240.00',

                'quantity' => '53',
                'image' => 'images/products/' . 20 .'.jpg',
                'category_id' => '4',
                'brand_id' => '12',
            ],
            [
                //'id' => 21,
                'name' => 'Stikwel 1L',
                'slug' => 'stikwel-1l',
                //'s_description' => 'Original 1 liter Water-based wood glue.',
                'description' => 'Low VOC water-based wood glue, Bond is stronger than the Wood. Also good for most porous materials or substrates like paper, textile, ceramic tiles (in dry areas), MDF (Medium Density Fiberboard), particle board, concrete (non-structural), etc.',
                'selling_price' => '180.00',

                'quantity' => '30',
                'image' => 'images/products/' . 21 .'.jpg',
                'category_id' => '4',
                'brand_id' => '13',
            ],
            [
                //'id' => 22,
                'name' => 'Stikwel 1/2L',
                'slug' => 'stikwel-1-2l',
                //'s_description' => 'Original 1/2 liter Water-Based wood glue.',
                'description' => 'Low VOC water-based wood glue, Bond is stronger than the Wood. Also good for most porous materials or substrates like paper, textile, ceramic tiles (in dry areas), MDF (Medium Density Fiberboard), particle board, concrete (non-structural), etc.',
                'selling_price' => '105.00',

                'quantity' => '30',
                'image' => 'images/products/' . 22 .'.jpg',
                'category_id' => '4',
                'brand_id' => '13',
            ],
            [
                //'id' => 23,
                'name' => 'PVC Wye Orange 3x2',
                'slug' => 'pvc-wye-orange-3x2',
                //'s_description' => 'A Y-shaped fitting with three openings used to create branch lines.',
                'description' => 'PVC wye fittings are designed to offer branch-like connectivity in a pipe line. They are similar in structure to a tee, but with the top branch protruding at a 45 degree angle instead of perpendicular to the other two outlets. We carry standard, reducing and double wye fittings in schedule 40 PVC, and have all sizes.',
                'selling_price' => '580.00',

                'quantity' => '50',
                'image' => 'images/products/' . 23 .'.jpg',
                'category_id' => '4',
                'brand_id' => '8',
            ],
            [
                //'id' => 24,
                'name' => 'PVC Tee 1/2',
                'slug' => 'pvc-tee-1-2',
                //'s_description' => 'PVC tee is a t-shaped pipe fitting.',
                'description' => 'PVC tee has good quality of high acid resistance alkali resistance chemicals resistance. widely used in water supply, chemical industry, water treatment, enviromental protection.',
                'selling_price' => '159.00',

                'quantity' => '125',
                'image' => 'images/products/' . 24 .'.jpg',
                'category_id' => '4',
                'brand_id' => '8',
            ],
            [
                //'id' => 25,
                'name' => 'PVC Elbow 45',
                'slug' => 'pvc-elbow-45',
                //'s_description' => 'Elbows used to change the angle or direction of the pipe run. Most commonly in 90 degrees and 45 degree turns.',
                'description' => 'This is used for plumbing decoration, homes, bathrooms, agricultural gardens, temperature heating systems, irrigation plumbing, solar water heaters, etc.',
                'selling_price' => '47.00',

                'quantity' => '225',
                'image' => 'images/products/' . 25 .'.jpg',
                'category_id' => '4',
                'brand_id' => '8',
            ],
            [
                //'id' => 26,
                'name' => 'Prestone Super Coolant 1L',
                'slug' => 'prestone-super-coolant-1l',
                //'s_description' => 'Preston radiator super coolant helped the vehicle(s) engines last longer with improved technology to allow longer lifespan.',
                'description' => 'Preston with patented formula to prevent corrosion, It helps the vehicle(s) cooling system work more efficiently and can last longer. Preston radiator super coolant compatible with all brands and coolant colors, It can be used in all brands and models of cars or light trucks.',
                'selling_price' => '1697.00',

                'quantity' => '15',
                'image' => 'images/products/' . 26 .'.jpg',
                'category_id' => '4',
                'brand_id' => '14',
            ],
            [
                //'id' => 27,
                'name' => 'Stanley Padlock 25mm',
                'slug' => 'stanley-padlock-25mm',
                //'s_description' => 'Standard shuckle padlocks are suited for both indoor or outdoor use.',
                'description' => 'These locks deliver strength,security and peace of mind for residential and commercial application.',
                'selling_price' => '149.00',

                'quantity' => '30',
                'image' => 'images/products/' . 27 .'.jpg',
                'category_id' => '4',
                'brand_id' => '4',
            ],
            [
                //'id' => 28,
                'name' => 'Steel Bar Stainless Round 3/4',
                'slug' => 'steel-bar-stainless-round-3-4',
                //'s_description' => 'Round stainless steel bar is a steel bar or mesh of steel used as a tension device in reinforced concrete.',
                'description' => 'Stainless steel reinforcement bars or rebars are used to improve the tensile strength of the concrete, since concrete is very weak in tension, but is strong in compression.',
                'selling_price' => '172.00',

                'quantity' => '73',
                'image' => 'images/products/' . 28 .'.jpg',
                'category_id' => '7',
                'brand_id' => '15',
            ],
            [
                //'id' => 29,
                'name' => 'Flat Bar 1/4 x 2 5 FT',
                'slug' => 'flat-bar-1-4-x-2-5-ft',
                //'s_description' => 'Flat bar steel is a general purpose steel alloy.',
                'description' => 'Flat bar steel can be easily welded or formed. It has a high resistance to heat and corrosion, and will respond well to hardening by cold working. Made up of 8 percent nickel and 18 percent chromium, it has good oxidation resistance when used in temperatures up to 1,600°F. This 304 stainless steel meets ASTM A276 specifications.',
                'selling_price' => '90.00',

                'quantity' => '21',
                'image' => 'images/products/' . 29 .'.jpg',
                'category_id' => '7',
                'brand_id' => '15',
            ],
            [
                //'id' => 30,
                'name' => 'Angle Bar A/B 3mm',
                'slug' => 'angle-bar-a-b-3mm',
                //'s_description' => 'Angle bar is a metal bracket in the form of a right angle.',
                'description' => 'Produced to extremely close tolerances to assist with all different applications. Cut to desired length. Great for scratch builders, modelers, machine shops, and architectural applications.',
                'selling_price' => '323.00',

                'quantity' => '86',
                'image' => 'images/products/' . 30 .'.jpg',
                'category_id' => '7',
                'brand_id' => '15',
            ],
            [
                //'id' => 31,
                'name' => 'Welding Rod 5/64 2.0mm',
                'slug' => 'welding-rod-5-64-2.0mm',
                //'s_description' => 'Suitable for DIY crafts, home decoration, electrical, engineering, Education, static models and more.',
                'description' => 'Megaweld M70 SeriesAWS 6013 Welding RodSize 2.0mm (5/64")20 Kilos per box.',
                'selling_price' => '485.00',

                'quantity' => '19',
                'image' => 'images/products/' . 31 .'.jpg',
                'category_id' => '7',
                'brand_id' => '15',
            ],
            [
                //'id' => 32,
                'name' => 'Angle Bar 2x2 3mm',
                'slug' => 'angle-bar-2x2-3mm',
                //'s_description' => 'Angle bar is a metal bracket in the form of a right angle.',
                'description' => 'Produced to extremely close tolerances to assist with all different applications. Cut to desired length. Great for scratch builders, modelers, machine shops, and architectural applications.',
                'selling_price' => '637.00',

                'quantity' => '100',
                'image' => 'images/products/' . 32 .'.jpg',
                'category_id' => '7',
                'brand_id' => '15',
            ],
            [
                //'id' => 33,
                'name' => 'Flat Bar 3/8x8',
                'slug' => 'flat-bar-3-8x8',
                //'s_description' => 'Flat bar steel is a general purpose steel alloy.',
                'description' => 'It has a high resistance to heat and corrosion, and will respond well to hardening by cold working. Made up of 8 percent nickel and 18 percent chromium, it has good oxidation resistance when used in temperatures up to 1,600°F. This 304 stainless steel meets ASTM A276 specifications.',
                'selling_price' => '70.00',

                'quantity' => '70',
                'image' => 'images/products/' . 33 .'.jpg',
                'category_id' => '7',
                'brand_id' => '15',
            ],
            [
                //'id' => 34,
                'name' => 'Steel Window Hinges Left & Right',
                'slug' => 'steel-window-hinges-left-right',
                //'s_description' => 'Window hinges is a mechanical bearing that connects two solid objects.',
                'description' => 'Typically allowing only a limited angle of rotation between them. Two objects connected by an ideal hinge rotate relative to each other about a fixed axis of rotation: all other translations or rotations being prevented, and thus a hinge has one degree of freedom. Hinges may be made of flexible material or of moving components. In biology, many joints function as hinges like the elbow joint.',
                'selling_price' => '30.00',

                'quantity' => '100',
                'image' => 'images/products/' . 34 .'.jpg',
                'category_id' => '7',
                'brand_id' => '15',
            ],
            [
                //'id' => 35,
                'name' => 'Plain Round Bar Ordinary 12mm',
                'slug' => 'plain-round-bar-ordinary-12mm',
                //'s_description' => 'Plain Round Bar is a type of rebar that has a smooth surface.',
                'description' => ' Round bar is commonly used to mesh in concrete slabs, and other infrastructure applications.',
                'selling_price' => '143.00',

                'quantity' => '74',
                'image' => 'images/products/' . 35 .'.jpg',
                'category_id' => '7',
                'brand_id' => '15',
            ],
            [
                //'id' => 36,
                'name' => 'Square Bar 16mm',
                'slug' => 'square-bar-16mm',
                //'s_description' => 'Sqare bar is used for turning, boring out, grooving, etc.',
                'description' => 'Sqare bar is a low-carbon iron offering a balance between strength, hardness and tenacity. With smooth surfaces, its use can vary from fabrication processes such as engine parts, welding, forging, us bearing and many more.',
                'selling_price' => '363.00',

                'quantity' => '22',
                'image' => 'images/products/' . 36 .'.jpg',
                'category_id' => '7',
                'brand_id' => '15',
            ],
            [
                //'id' => 37,
                'name' => 'Republic Cement',
                'slug' => 'republic-cement',
                //'s_description' => 'The natural mineral component (philippine tuff) ensures increased strengh and durability over time.',
                'description' => 'Republic Cement is a premium sulfate-resistant Portland Cement that exceeds the strength and conforms to the chemical and physical requirements of ASTM C150 for Type II Cement.',
                'selling_price' => '230.00',

                'quantity' => '322',
                'image' => 'images/products/' . 37 .'.jpg',
                'category_id' => '8',
                'brand_id' => '16',
            ],
            [
                //'id' => 38,
                'name' => 'Fortune Cement',
                'slug' => 'fortune-cement',
                //'s_description' => 'Fortune cement is a premium quality blended cement.',
                'description' => ' It uses special technology that makes concrete mix denser, more bonded and more workable for strong and beautiful structures you can be proud of. It is a blended cement that uses high quality fly ash to enhance its workability and long-term durability.',
                'selling_price' => '270.00',

                'quantity' => '550',
                'image' => 'images/products/' . 38 .'.jpg',
                'category_id' => '8',
                'brand_id' => '16',
            ],
            [
                //'id' => 39,
                'name' => 'Front Doorknob',
                'slug' => 'front-doorknob',
                //'s_description' => 'A door handle or door knob is a mechanism used to open or close a door.',
                'description' => 'Door Knob Lockset with 3 Keys Privacy Handle Bedroom Bathroom Handle Lockset Stainless Steel Polished Door Knob Set Interior Lockable.',
                'selling_price' => '230.00',

                'quantity' => '322',
                'image' => 'images/products/' . 39 .'.jpg',
                'category_id' => '9',
                'brand_id' => '17',
            ],
            [
                //'id' => 40,
                'name' => 'PVC Door 60x190 With Louver Pad',
                'slug' => 'pvc-door-60x190-with-louver-pad',
                //'s_description' => 'PVC door for bathroom with free doorknob.',
                'description' => 'PVC Door for comfort room. It comes with Door Jamb, louver, door pad and free door knob.',
                'selling_price' => '1400.00',

                'quantity' => '3',
                'image' => 'images/products/' . 40 .'.jpg',
                'category_id' => '9',
                'brand_id' => '18',
            ],
            [
                //'id' => 41,
                'name' => 'Welding Machine Inverter Type 160 A',
                'slug' => 'welding-machine-inverter-type-160-a',
                //'s_description' => 'Welding machine is used for welding grills, doors, steel plates, Iron tanks, and most metal materials.',
                'description' => '160 Ampersand welding machine with Higher Output(%) 15% to 20% more than other machines. Easy to operate and safe to use.',
                'selling_price' => '6700.00',

                'quantity' => '3',
                'image' => 'images/products/' . 41 .'.jpg',
                'category_id' => '10',
                'brand_id' => '19',
            ],
            [
                //'id' => 42,
                'name' => 'Welding Machine Yamato Inverter 300 A',
                'slug' => 'welding-machine-yamato-inverter-300-a',
                //'s_description' => 'Welding machine is used for welding grills, doors, steel plates, Iron tanks, and most metal materials.',
                'description' => '300 Ampersand welding machine with High Efficiency, Higher Output 15% to 20% more than other machines, and Easy to operate and safe to use.',
                'selling_price' => '11000.00',

                'quantity' => '1',
                'image' => 'images/products/' . 42 .'.jpg',
                'category_id' => '10',
                'brand_id' => '20',
            ],
            [
                //'id' => 43,
                'name' => 'Adjustable Wrench',
                'slug' => 'adjustable-wrench',
                //'s_description' => 'Used for plumbing, automotive or home use.',
                'description' => 'Variable opening wrenches for outside hexagon nuts, bolt and screws.',
                'selling_price' => '430.00',

                'quantity' => '50',
                'image' => 'images/products/' . 43 .'.jpg',
                'category_id' => '10',
                'brand_id' => '4',
            ],
            [
                //'id' => 44,
                'name' => 'Powerhouse Trowel',
                'slug' => 'powerhouse-trowel',
                //'s_description' => 'Powerhouse is a small hand tool used for digging, applying, smoothing, or moving small amounts of viscous or particulate material.',
                'description' => 'Best for Plastering and skimming cement. Bricklaying trowel w/ plastic handle.',
                'selling_price' => '295.00',

                'quantity' => '55',
                'image' => 'images/products/' . 44 .'.jpg',
                'category_id' => '10',
                'brand_id' => '21',
            ],
            [
                //'id' => 45,
                'name' => 'Tape Measure 3m',
                'slug' => 'tape-measure-3m',
                //'s_description' => 'Tape measure is used to measure distance.',
                'description' => 'Fall resistant leather cover 3 meters tape measure paint white ruler tape. Measuring ratio currently 2 upper and lower sides.',
                'selling_price' => '150.00',

                'quantity' => '25',
                'image' => 'images/products/' . 45 .'.jpg',
                'category_id' => '10',
                'brand_id' => '4',
            ],
            [
                //'id' => 46,
                'name' => 'Tape Measure 5m',
                'slug' => 'tape-measure-5m',
                //'s_description' => 'Tape measure is used to measure distance.',
                'description' => 'Fall resistant leather cover 5 meters tape measure paint white ruler tape. Measuring ratio currently 2 upper and lower sides.',
                'selling_price' => '230.00',

                'quantity' => '15',
                'image' => 'images/products/' . 46 .'.jpg',
                'category_id' => '10',
                'brand_id' => '4',
            ],
            [
                //'id' => 47,
                'name' => 'Paint Tray',
                'slug' => 'paint-tray',
                //'s_description' => 'Paint tray is typically having a well and a ridged slope with which to spread paint evenly over the roller.',
                'description' => 'Used to hold paint for decorating with a paint roller, and for mixing paints to achieve the color you want.',
                'selling_price' => '45.00',

                'quantity' => '70',
                'image' => 'images/products/' . 47 .'.jpg',
                'category_id' => '10',
                'brand_id' => '21',
            ],
            [
                //'id' => 48,
                'name' => 'Claw Hammer',
                'slug' => 'claw-hammer',
                //'s_description' => 'Claw hammer is made from drop-forged carbon steel, heat treated, ground, and polished.',
                'description' => 'Hammerhead consists of one side flat with a smooth surface for impacting another surface, while the other side is split and curved (claw-shaped), for extracting nails.',
                'selling_price' => '276.00',

                'quantity' => '80',
                'image' => 'images/products/' . 48 .'.jpg',
                'category_id' => '10',
                'brand_id' => '4',
            ],
            [
                //'id' => 49,
                'name' => 'Boysen Aryclic Color Yellow 1L',
                'slug' => 'boysen-aryclic-color-yellow-1l',
                //'s_description' => 'is a 100% acrylic latex paint with excellent hiding, durability and dirt pick – up resistance.',
                'description' => 'They disperse easily and produce tints from pastel to medium shades with even finishes. To produce dark shades, choose from factory mixed colors, Mix-and-Match outlets, or intermix premixed colors to get desired shade. Ideal ratio of tinting color to paint is 1:16, respectively.',
                'selling_price' => '167.00',

                'quantity' => '35',
                'image' => 'images/products/' . 49 .'.jpg',
                'category_id' => '1',
                'brand_id' => '22',
            ],
            [
                //'id' => 50,
                'name' => 'Boysen Tinting Color Black 1/4L',
                'slug' => 'boysen-tinting-color-black-1-4l',
                //'s_description' => 'is a 100% acrylic latex paint with excellent hiding, durability and dirt pick – up resistance.',
                'description' => 'Boysen Oil Tinting Colors are concentrated alkyd based tinting paints for oil, alkyd and enamel paints. They are used to produce tints from pastel to medium shades. NOTE: To produce dark shades, choose from factory mixed colors or intermix premixed colors to get desired shade.',
                'selling_price' => '70.00',

                'quantity' => '35',
                'image' => 'images/products/' . 50 .'.jpg',
                'category_id' => '1',
                'brand_id' => '22',
            ],
            
        ];

        Product::insert($products);
    }
}
